sudo: required

language: java

jdk:
  - oraclejdk8

services:
  - docker
install:
  - mvn install -Dmaven.javadoc.skip=true -B -V

before_install:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

after_success:
  - docker build -t fgiana/stock .
  - docker run --name stock -d -P fgiana/stock
  - docker ps
  - docker port stock
  - docker push fgiana/stock

